source "https://rubygems.org"
ruby '1.9.3'
gem 'bson_ext'
gem 'mongooz', :git=>'https://github.com/tonysweefee/mongooz.git'
gem 'sass'
gem 'compass'
gem 'haml'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'omniauth'
gem 'omniauth-google-oauth2'